config/routes.rb
WayOfTheGymja::Application.routes.draw do
  devise_for :users

  namespace "api" do
    scope "users/:user_id/" do
  		resources :workouts, :only => [:index]
    end

    resources :workouts, :only => [:show, :destroy, :create]
    resources :activity_bases, :only => [:index]
  end

  resources :users, :only => [:index, :show]

  get "track", :to => "static_pages#track"
  root :to => "static_pages#root"
end

app/models/activity.rb
class Activity < ActiveRecord::Base
	attr_accessible :workout_id, :activity_base_id

	validates :activity_base_id, :presence => true

	belongs_to :workout, :inverse_of => :activities
	belongs_to :activity_base
	has_many :activity_sets, :inverse_of => :activity
end

app/models/activity_base.rb
class ActivityBase < ActiveRecord::Base
  attr_accessible :set_type, :name, :description, :flavor

  validates :set_type, :name, :description, :presence => true
  validates :name, :uniqueness => true

  has_many :activities
end

app/models/activity_set.rb
class ActivitySet < ActiveRecord::Base
  attr_accessible :set_number, :type, :activity_id

  validates :set_number, :type, :presence => true

  belongs_to :activity, :inverse_of => :activity_sets
end

app/models/distance.rb
class Distance < ActivitySet
	attr_accessible :duration, :distance

	validates :duration, :distance, :presence => true
	validates :repetitions, :weight, :intensity, :inclusion => {
		:in => [nil] }
	
end

app/models/distance_set.rb
class DistanceSet < ActivitySet
	attr_accessible :duration, :distance

	validates :duration, :distance, :presence => true
	validates :repetitions, :weight, :intensity, :inclusion => {
		:in => [nil] }
	
end

app/models/duration.rb
class Duration < ActivitySet
	attr_accessible :duration

	validates :duration, :presence => true
	validates :repetitions, :weight, :intensity, :distance, :inclusion => {
		:in => [nil] }
	
end

app/models/duration_set.rb
class DurationSet < ActivitySet
	attr_accessible :duration

	validates :duration, :presence => true
	validates :repetitions, :weight, :intensity, :distance, :inclusion => {
		:in => [nil] }
	
end

app/models/general.rb
class General < ActivitySet
	attr_accessible :duration, :intensity

	validates :duration, :intensity, :presence => true
	validates :repetitions, :weight, :distance, :inclusion => { :in => [nil] }
end

app/models/general_set.rb
class GeneralSet < ActivitySet
	attr_accessible :duration, :intensity

	validates :duration, :intensity, :presence => true
	validates :repetitions, :weight, :distance, :inclusion => { :in => [nil] }
end

app/models/repetition.rb
class Repetition < ActivitySet
	attr_accessible :repetitions

	validates :repetitions, :presence => true
	validates :intensity, :weight, :distance, :duration, :inclusion => { 
		:in => [nil] }
end

app/models/repetition_set.rb
class RepetitionSet < ActivitySet
	attr_accessible :repetitions

	validates :repetitions, :presence => true
	validates :intensity, :weight, :distance, :duration, :inclusion => { 
		:in => [nil] }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :gender, :birthday, :height, :clan, :username

  validates :gender, :inclusion => { :in => ["male", "female"] }
  validates :height, :numericality => { :greater_than => 0, :only_integer => true}

  has_many :workouts, :inverse_of => :user
end

app/models/weight.rb
class Weight < ActivitySet
	attr_accessible :weight, :repetitions

	validates :weight, :repetitions, :presence => true
	validates :intensity, :distance, :duration, :inclusion => { :in => [nil] }
end

app/models/weight_set.rb
class WeightSet < ActivitySet
	attr_accessible :weight, :repetitions

	validates :weight, :repetitions, :presence => true
	validates :intensity, :distance, :duration, :inclusion => { :in => [nil] }
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :logged_date, :user_id

  validates :logged_date, :user_id, :presence => true

  belongs_to :user, :inverse_of => :workouts
  has_many :activities, :inverse_of => :workout
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])

		render :show
	end

	def index
		@users = User.all

		render :index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WayOfTheGymja</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script>
    <% if current_user %>
    	WayOfTheGymja.current_user = <%= current_user.id %>
    <% end %>
  </script>
</head>



<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="<%= root_url %>">Way of the Gymja</a>
    <ul class="nav">
      <!-- <li class="active"><a href="#"></a></li> -->
      <% if current_user %>
        <li><a id="profile-nav" href="<%= user_url(current_user) %>"><i class="icon-user"></i></a></li>
        <li><a id="track-nav" href="<%= track_url %>"><i class="icon-pencil"></i></a></li>
        <li><a id="logout-nav" data-method="delete" href="<%= destroy_user_session_url %>"><i class="icon-off"></i></a></li>
        <script>
            $('#profile-nav').tooltip({ animation:true, placement:"bottom", delay:100, title:"Profile" })
            $('#track-nav').tooltip({ animation:true, placement:"bottom", delay:100, title:"Track" })
            $('#logout-nav').tooltip({ animation:true, placement:"bottom", delay:100, title:"Logout" })
        </script>
      <% end %>
    </ul>
  </div>
</div>

<!-- 
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p> -->

<div class="row logo-row">
  <img class="logo" src="https://s3-us-west-1.amazonaws.com/gymja/TheNinjaReview.gif"></img>
</div>

<a href="https://github.com/BitPuncher"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>

<div class="content">
  <%= yield %>
</div>

<div class="footer">
  <div class="row-fluid">
    <div class="span4 text-left">Copyright Jefferson Leard 2013</div>
    <div class="span4 text-center">Way of the Gymja</div>
    <div class="span4 text-right">Go Internet Go</div>
  </div>
</div>

</body>
</html>